--- # 优先次序高
CHATROOM:
  NGINX:
    CONFS:
      - HTTP_PORT: 80
        ROOT: '/var/www/chatroom-service_socket_backend-sockeio/public'
        SERVER_NAME: 'dev.socket.chatroom.ques98.cn'
        INDEX: 'index.html index.htm'
        # TRY_FILES: '$uri $uri/ /index.php?$query_string'
        PROXY_PASS: 'http://127.0.0.1:4011/'
      - HTTP_PORT: 80
        ROOT: '/var/www/chatroom-service_any_frontend-vue/dist'
        SERVER_NAME: 'dev.chatroom.ques98.cn'
        INDEX: 'index.html index.htm'
        TRY_FILES: '$uri $uri/ /index.html'