--- # 优先次序高
CHATROOM:
  SOCKET:
    HOST: 'fea.socket.chatroom.ques98.cn'
  STORAGE:
    HOST: 'fea.socket.chatroom.ques98.cn'
  HTTP:
    HOST: 'fea.api.service.chatroom.ques98.cn'
  NGINX:
    CONFS:
      - HTTP_PORT: 80
        ROOT: '/var/www/chatroom-service_socket_backend-socketio/public'
        SERVER_NAME: 'fea.socket.chatroom.ques98.cn'
        INDEX: 'index.html index.htm'
        # TRY_FILES: '$uri $uri/ /index.php?$query_string'
        LOCATIONS:
          - PATH: '~* \.io'
            PROXY_PASS: 'http://127.0.0.1:4003' # 不可 / 结尾
        # ADD_HEADERS:
#           - "Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS'"
#           - "Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"
# 

      - HTTP_PORT: 80
        ROOT: '/var/www/chatroom-service_other_backend-koa/public'
        SERVER_NAME: 'fea.api.service.chatroom.ques98.cn'
        INDEX: 'index.html index.htm'
        # TRY_FILES: '$uri $uri/ /index.php?$query_string'
        LOCATIONS:
          - PATH: '/'
            PROXY_PASS: 'http://127.0.0.1:4002' # 不可 / 结尾
        # ADD_HEADERS:
#           - "Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS'"
#           - "Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"
# 
      - HTTP_PORT: 80
        ROOT: '/var/www/chatroom-service_any_frontend-vue/dist'
        SERVER_NAME: 'fea.chatroom.ques98.cn'
        INDEX: 'index.html index.htm'
        LOCATIONS:
          - PATH: '/'
            TRY_FILES: '$uri $uri/ /index.html'
   
      - HTTP_PORT: 80
        ROOT: '/var/www/chatroom-admin_any_backend-fastadmin/public'
        SERVER_NAME: 'fea.admin.chatroom.ques98.cn'
        INDEX: 'index.php index.html index.htm'
        LOCATIONS:
          - PATH: '~* \.php$'
            ADD_HEADERS:
              - "Access-Control-Allow-Origin '*'"
              - "Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS'"
              - "Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"
              - "Access-Control-Allow-Credentials true"
            FASTCGI_PASS: '127.0.0.1:9073'
            FASTCGI_INDEX: 'index.php'
            FASTCGI_SPLIT_PATH_INFO: '^(.+\.php)(.*)$'
            FASTCGI_PARAM: 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
            INCLUDE: '/etc/nginx/fastcgi_params'
  MYSQL:
    HOST: '127.0.0.1'
    PORT: 3306
    DATABASE: 'chatroom'
    USERNAME: 'backend'
    PASSWORD: 'mysql_pass_backend'
  MONGODB:
    HOST: '127.0.0.1'
    PORT: 27017
    DATABASE: 'chatroom'
    USERNAME: 'backend'
    PASSWORD: 'mongodb_pass_backend'
  DRIVERS:
    ONE:
      LOGIN_STATE_URL: 'http://test.c368.com/apiapp/5d1cb62aa5488'
      MONEY_STATE_URL: 'http://test.c368.com/apiapp/5d1cb646059d8'