--- # 优先次序高
filebeat_version: 6.5.4
FILEBEAT:
  PROSPECTORS:
    PATHS:
      - /home/vagrant/www/landan-service_backend-golang/storage/.log/*.log
      - /home/centos/www/landan-service_backend-golang/storage/.log/*.log
      - /home/vagrant/www/landan-admin_backend-lumen/storage/.log/*.log
      - /home/centos/www/landan-admin_backend-lumen/storage/.log/*.log
  OUTPUT:
    LOGSTASH:
      HOSTS:
        - "127.0.0.1:5044"