--- # 优先次序高
NGINX:
  CONFS:
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/landan-service_backend-lumen/public'
      SERVER_NAME: 'fea.landan.com'
      PHP_VERSION: '5.6'
    - HTTP_PORT: 80
      ROOT: '/home/vagrant/www/landan-admin_backend-lumen/public'
      SERVER_NAME: 'fea.admin.landan.com'
      PHP_VERSION: '7.3'