---
# supervisord 指的是 supervisord 守护进程 管理器
# supervisor  指的是 被管理的那些 php, python 等 进程
SUPERVISOR:
  FILE: '/var/run/supervisord/supervisord.sock'
  PIDFILE: '/var/run/supervisord/supervisord.pid'
  PORT: '*:9001'
  LOGFILE: '/var/log/supervisord/supervisord.log'
  SERVERURL: 'unix:///var/run/supervisord/supervisord.sock'
  FILES: '/etc/supervisor/conf.d/*.conf'
  USERNAME: 'backend'
  PASSWORD: 'supervisor_pass'
  PIDID: 'var/lib/supervisord/supervisord.pid'
  CONFS:
    - GROUP: 'lottery-crawler_all_backend-scrapy'
      PROGRAMS:
        - PROGRAM: 'python3_src_schedules_lottery_issue_lottery_request_types_multiple_queue_true_index'
          DIRECTORY: '/var/www/lottery-crawler_all_backend-scrapy'
          COMMAND: '/usr/bin/python3 /var/www/lottery-crawler_all_backend-scrapy/src/schedules/lottery_issue_lottery_request_types_multiple_queue_true/index.py'
          PROCESS_NAME: '%(program_name)s-%(process_num)s'
          NUMPROCS: 1
          AUTOSTART: true
          AUTORESTART: true
          STARTSECS: 1
          STARTRETRIES: -1 
          STDOUT_LOGFILE: '/var/log/supervisor/lottery-crawler_all_backend-scrapy-python3_src_schedules_lottery_issue_lottery_request_types_multiple_queue_true_index.log'
          REDIRECT_STDERR: true
          EXITCODES: 0
          NOTE: '高频率 采集 最新采种 API 数据'
        - PROGRAM: 'python3_src_schedules_lottery_issue_lottery_request_types_single_queue_true_index'
          DIRECTORY: '/var/www/lottery-crawler_all_backend-scrapy'
          COMMAND: '/usr/bin/python3 /var/www/lottery-crawler_all_backend-scrapy/src/schedules/lottery_issue_lottery_request_types_single_queue_true/index.py'
          PROCESS_NAME: '%(program_name)s-%(process_num)s'
          NUMPROCS: 1
          AUTOSTART: true
          AUTORESTART: true
          STARTSECS: 1
          STARTRETRIES: -1 
          STDOUT_LOGFILE: '/var/log/supervisor/lottery-crawler_all_backend-scrapy-python3_src_schedules_lottery_issue_lottery_request_types_single_queue_true_index.log'
          REDIRECT_STDERR: true
          EXITCODES: 0
          NOTE: '次频率 采集 当天采种 API 数据'

    - GROUP: 'lottery-service_resource_backend-lumen'
      PROGRAMS:
        - PROGRAM: 'php73_artisan_swoole_http_start'
          DIRECTORY: '/var/www/lottery-service_resource_backend-lumen'
          COMMAND: '/usr/bin/php73 /var/www/lottery-service_resource_backend-lumen/artisan swoole:http start'
          PROCESS_NAME: '%(program_name)s-%(process_num)s'
          NUMPROCS: 1
          AUTOSTART: true
          AUTORESTART: true
          STARTSECS: 1
          STARTRETRIES: -1 
          STDOUT_LOGFILE: '/var/log/supervisor/lottery-service_resource_backend-lumen-php73_artisan_swoole_http_start.log'
          REDIRECT_STDERR: true
          EXITCODES: 0
          NOTE: "Swoole + PHP HTTP server"

        - PROGRAM: 'php73_artisan_command_lottery_issue_announce_to_database_by_queue'
          DIRECTORY: '/var/www/lottery-service_resource_backend-lumen'
          COMMAND: '/usr/bin/php73 /var/www/lottery-service_resource_backend-lumen/artisan command:lottery-issue:announce-to-database-by-queue'
          PROCESS_NAME: '%(program_name)s-%(process_num)s'
          NUMPROCS: 1
          AUTOSTART: true
          AUTORESTART: true
          STARTSECS: 1
          STARTRETRIES: -1 
          STDOUT_LOGFILE: '/var/log/supervisor/lottery-service_resource_backend-lumen-php73_artisan_command_lottery_issue_announce_to_database_by_queue.log'
          REDIRECT_STDERR: true
          EXITCODES: 0
          NOTE: "对列 开奖"
          
        - PROGRAM: 'php73_artisan_command_lottery_issue_accumulate_to_database_by_queue'
          DIRECTORY: '/var/www/lottery-service_resource_backend-lumen'
          COMMAND: '/usr/bin/php73 /var/www/lottery-service_resource_backend-lumen/artisan command:lottery-issue:accumulate-to-database-by-queue'
          PROCESS_NAME: '%(program_name)s-%(process_num)s'
          NUMPROCS: 1
          AUTOSTART: true
          AUTORESTART: true
          STARTSECS: 1
          STARTRETRIES: -1 
          STDOUT_LOGFILE: '/var/log/supervisor/lottery-service_resource_backend-lumen-php73_artisan_command_lottery_issue_accumulate_to_database_by_queue.log'
          REDIRECT_STDERR: true
          EXITCODES: 0
          NOTE: "对列 累计(长龙)"
