---
# - name: command mysql_upgrade --force -uroot
#   command: mysql_upgrade --force -u root
- name: (template) scp tmp/lottery.sql.j2 /tmp/lottery.sql
  template:
    src: tmp/lottery.sql.j2
    dest: /tmp/lottery.sql
    owner: root
    group: root
    mode: 0775
- name: "(shell) mysql --user={{ MYSQL.SERVERS[0].CONNECTIONS[0]['USER'] }} --password='{{ MYSQL.SERVERS[0].CONNECTIONS[0]['PASSWORD'] }}' --force < /tmp/lottery.sql"
  shell: "mysql --user={{ MYSQL.SERVERS[0].CONNECTIONS[0]['USER'] }} --password='{{ MYSQL.SERVERS[0].CONNECTIONS[0]['PASSWORD'] }}' --force < /tmp/lottery.sql"
  run_once: yes
