# 安裝 MySQL 5.6 預設 無密碼
---
## MYSQL CLUSTER NDB (启动) 部分
- import_tasks: yum-install-mysql_cluster.yml
- import_tasks: service-mysqld-restarted.yml # when service mysqld start at the first time, should not template /etc/my.cnf
