---
- name: "(git) git clone git@gitlab.ques98.cn:lottery/lottery-service_resource_backend-lumen.git /var/www/lottery-service_resource_backend_lumen"
  git:
    repo: 'git@gitlab.ques98.cn:lottery/lottery-service_resource_backend-lumen.git'
    dest: "/var/www/lottery-service_resource_backend_lumen"
    version: "{{ 'develop' if branch in ['fea', 'feature'] else branch }}"
    clone: yes
    update: yes
    accept_hostkey: yes
  become: no # 使用 vagrant:vagrant git clone 下来， 不使用 root git clone
  
- name: (shell) composer install
  shell: composer install
  become: no # 使用 vagrant:vagrant yarn --no-bin-links
  args:
    chdir: "/var/www/lottery-service_resource_backend_lumen"
  register: s_composer_install
  notify: debug composer install
  
# chmod -R 700 /root/.ssh/id_rsa
# chmod -R 700 /root/.ssh/id_rsa.pub
# key must be put in root because sudo git clone