---
- name: "(git) git clone git@gitlab.ques98.cn:lottery/lottery-crawler_all_backend-scrapy.git /var/www/lottery-crawler_all_backend-scrapy"
  git:
    repo: 'git@gitlab.ques98.cn:lottery/lottery-crawler_all_backend-scrapy.git'
    dest: "/var/www/lottery-crawler_all_backend-scrapy"
    version: "{{ 'develop' if branch in ['fea', 'feature'] else branch }}"
    clone: yes
    update: yes
    accept_hostkey: yes
  become: no # 使用 vagrant:vagrant git clone 下来， 不使用 root git clone

- name: (shell) pip3 install -r requirement.txt
  shell: pip3 install -r requirement.txt
  args:
    chdir: "/var/www/lottery-crawler_all_backend-scrapy"
  register: s_pip3_install
  


# chmod -R 700 /root/.ssh/id_rsa
# chmod -R 700 /root/.ssh/id_rsa.pub
# key must be put in root because sudo git clone