---
# - name: command mysql_upgrade --force -uroot
#   command: mysql_upgrade --force -u root
- name: (template) scp tmp/lottery.sql.j2 /tmp/lottery.sql
  template:
    src: tmp/lottery.sql.j2
    dest: /tmp/lottery.sql
    owner: root
    group: root
    mode: 0776
    backup: no

- name: (shell) mysql < /tmp/lottery.sql
  shell: mysql < /tmp/lottery.sql


# - name: command mysql_upgrade --force -uroot
#   command: mysql_upgrade --force -u root
- name: (template) scp tmp/grant.sql.j2 /tmp/grant.sql
  template:
    src: tmp/grant.sql.j2
    dest: /tmp/grant.sql
    owner: vagrant
    group: vagrant
    mode: 0755
- name: "(shell) mysql --user='root' --password='mysql_pass_cli' --force < /tmp/grant.sql"
  shell: "mysql --user='root' --password='mysql_pass_cli' --force < /tmp/grant.sql"
