---
- name: "(file) rm -Rf /etc/nginx/conf.d/*.conf"
  file:
    state: absent
    path: "{{ item }}"
  with_fileglob: '/etc/nginx/conf.d/*.conf'
- name: (template) scp etc/nginx/nginx.conf.j2 /etc/nginx/nginx.conf
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0776
    backup: no
    validate: nginx -t -c %s
- name: (template) scp etc/nginx/conf.d/default.conf.j2 /etc/nginx/conf.d/*.conf
  template:
    src: etc/nginx/conf.d/default.conf.j2
    dest: "/etc/nginx/conf.d/{{ CONF['SERVER_NAME'] }}.conf"
    owner: root
    group: root
    mode: 0776
    backup: no
    #validate: nginx -t -c /etc/nginx/nginx.conf
  with_items: "{{ NGINX.CONFS }}"
  loop_control:
    loop_var: CONF
  # notify: start nginx
