---
## MYSQL MMM HA 节点部分
- import_tasks: template-etc_hosts.yml
- import_tasks: yum-install-mysql_mmm.yml
- import_tasks: template-etc_mysql_mmm_mmm_common_conf.yml
- import_tasks: template-etc_mysql_mmm_mmm_agent_conf.yml
- import_tasks: service-mysql_mmm_agent-restarted.yml



