---
- name: (template) scp etc/nginx/conf.d/default.conf.j2 /etc/nginx/conf.d/*.conf
  template:
    src: etc/nginx/conf.d/default.conf.j2
    dest: "/etc/nginx/conf.d/{{ CONF['SERVER_NAME'] }}.conf"
    owner: root
    group: root
    mode: 0776
    backup: no
    #validate: nginx -t -c /etc/nginx/nginx.conf
  with_items: "{{ LOTTERY_NGINX.CONFS }}"
  loop_control:
    loop_var: CONF
  # notify: start nginx
