---
- name: "(git) git clone git@github.com:landan789/landan-www_backend-koa.git {{ LANDAN_WWW_BACKEND_KOA.DEST }}"
  git:
    repo: 'git@github.com:landan789/landan-www_backend-koa.git'
    dest: "{{ LANDAN_WWW_BACKEND_KOA.DEST }}"
    version: "{{ 'develop' if branch == 'feature' or branch == 'fea' else branch }}"
    clone: yes
    update: yes
    accept_hostkey: yes
  become: no # 使用 vagrant:vagrant git clone 下来， 不使用 root git clone
  register: s_landan_www_backend_koa_version
  notify: debug git clone landan-www_backend-koa
# chmod -R 700 /root/.ssh/id_rsa
# chmod -R 700 /root/.ssh/id_rsa.pub
# key must be put in root because sudo git clone