---
- name: (yum) yum remove mariadb-libs mysql*
  yum: 
    name: 
      - mariadb-libs
      - mysql*
    state: absent

- name: (yum) yum insatll epel-release-latest-7.noarch.rpm
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    allow_downgrade: True
- name: (yum) yum insatll mysql-cluster-community-data-node-7.6.9-1.el7.x86_64.rpm
  yum: 
    name: https://dev.mysql.com/get/Downloads/MySQL-Cluster-7.6/mysql-cluster-community-data-node-7.6.9-1.el7.x86_64.rpm
    allow_downgrade: True
  notify: debug yum install cluster_ndb
 
  