# 安裝 MySQL 5.6 預設 無密碼
---
## MYSQL MHA HA MASTERHA 部分
- import_tasks: yum-install-master_manager.yml
- import_tasks: template-etc_masterha_defualt_cnf.yml
- import_tasks: template-etc_master_app_cnf.yml
- import_tasks: template-etc_master_scripts_master_ip_failover.yml
- import_tasks: template-etc_master_scripts_master_ip_online_change.yml
- import_tasks: file-mkdir-var_log_masterha.yml
- import_tasks: lineinfile-root_ssh_authorized_keys.yml
- import_tasks: shell-masterha_manager.yml
