---
- name: "(shell) nohup masterha_manager --conf={{ MASTERHA.CONF }} --remove_dead_master_conf --ignore_last_failover < /dev/null > {{ MASTERHA.MANAGER_LOG }} 2>&1 &"
  shell: "nohup masterha_manager --conf={{ MASTERHA.CONF }} --remove_dead_master_conf --ignore_last_failover < /dev/null > {{ MASTERHA.MANAGER_LOG }} 2>&1 &"
  notify: 
    - debug yum install master manager