---
- name: "(shell) sudo ndb_mgm -e 'show'"
  shell: "sudo ndb_mgm -e 'show'"
  register: string_ndb_show
  ignore_errors: yes
- name: (debug) string_ndb_show
  debug: 
    msg: "{{ string_ndb_show }}"  