---
- import_tasks: git-clone-lottery-crawler_all_backend_scrapy.yml
- import_tasks: shell-pip3-install-requirement_txt.yml
- import_tasks: supervisorctl-restarted-lottery_crawler_all_backend_scrapy.yml