---
- name: (yum) yum insatll epel-release-latest-7.noarch.rpm
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    allow_downgrade: True
- name: (yum) yum remove  mysql-mmm-agent mysql-mmm-monitor
  yum: 
    name:
      - mysql-mmm-agent
      - mysql-mmm-monitor
    state: absent

- name: (yum) yum install  mysql-mmm-agent mysql-mmm-monitor
  yum: 
    name:
      - mysql-mmm-agent
      - mysql-mmm-monitor
    state: latest
  notify: debug yum install mysql-mmm monitor
