# 安裝 MySQL 5.6 預設 無密碼
---
- import_tasks: file-mkdir-var_log_mysql.yml
- import_tasks: set_fact-mysql_skip_true.yml
- import_tasks: template-etc_my_cnf.yml
- import_tasks: service-mysqld-restarted.yml
- import_tasks: shell-mysql-tmp_update_user_sql.yml
- import_tasks: set_fact-mysql_skip_false.yml
- import_tasks: template-etc_my_cnf.yml
- import_tasks: service-mysqld-restarted.yml
- import_tasks: shell-mysql-tmp_grant_sql.yml
- import_tasks: shell-mysql-tmp_alter_user_sql.yml
- import_tasks: shell-mysql-tmp_create_sql.yml
- import_tasks: shell-mysql-tmp_landan_sql.yml
- import_tasks: shell-mysql-tmp_nuoya_sql.yml
- import_tasks: shell-mysql-tmp_cms_sql.yml
