- name: (file) mkdir /usr/mysql-cluster
  file:
    path: /usr/mysql-cluster
    state: directory
    mode: 0775

- name: "(template) scp etc/mgm.ini.j2 /etc/mgm.ini"
  template:
    src: etc/mgm.ini.j2
    dest: /etc/mgm.ini
    owner: mysql
    group: mysql
    mode: 0775
