- name: (file) mkdir /usr/mysql-cluster
  file:
    path: /usr/mysql-cluster
    state: directory
    mode: 0755

- name: "(template) scp etc/mgm.ini.j2 /etc/mgm.ini"
  template:
    src: etc/mgm.ini.j2
    dest: /etc/mgm.ini
    owner: root
    group: root
    mode: 0755
