---
- name: "(file) rm -Rf /etc/supervisor/conf.d/*.conf"
  file:
    state: absent
    path: "{{ item }}"
  with_fileglob: '/etc/supervisor/conf.d/*.conf'
- name: (template) scp etc/supervisor/conf.d/default.conf.j2 /etc/supervisor/conf.d/*.conf
  template:
    src: etc/supervisor/conf.d/default.conf.j2
    dest: "/etc/supervisor/conf.d/{{ CONF['GROUP'] }}.conf"
    owner: root
    group: root
    mode: 0776
    backup: no
    #validate: nginx -t -c /etc/nginx/nginx.conf
  with_items: "{{ SUPERVISOR.CONFS }}"
  loop_control:
    loop_var: CONF
  # notify: start nginx
