# 安裝 MySQL 5.6 預設 無密碼
---
- import_tasks: shell-mysqldump.yml
- import_tasks: yum-install-yum_utils.yml
- import_tasks: yum-install-mysql_comunnity_server.yml
- import_tasks: service-mysqld-restarted.yml # when service mysqld start at the first time, should not template /etc/my.cnf
- import_tasks: file-mkdir-var_log_mysql.yml
- import_tasks: template-etc_my_cnf-before_grant.yml
- import_tasks: service-mysqld-restarted.yml
- import_tasks: shell-mysql-tmp_update_user_sql.yml
- import_tasks: service-mysqld-restarted.yml
- import_tasks: template-etc_my_cnf.yml # 之後的 MySQL 才會寫 BINLOG 
- import_tasks: service-mysqld-restarted.yml
- import_tasks: shell-mysql-tmp_grant_sql.yml
- import_tasks: shell-mysql-tmp_alter_user_sql.yml
- import_tasks: shell-mysql-tmp_create_sql.yml
- import_tasks: shell-mysql-tmp_landan_sql.yml
- import_tasks: shell-mysql-tmp_cms_sql.yml
- import_tasks: shell-mysql-tmp_change_master_sql.yml