# 安裝 MySQL 5.6 預設 無密碼
---
- import_tasks: shell-mysqldump.yml
- import_tasks: yum-install-yum_utils.yml
- import_tasks: yum-install-mysql_comunnity_server.yml
- import_tasks: service-mysqld-restarted.yml # when service mysqld start at the first time, should not template /etc/my.cnf