---

- name: (file) mkdir /var/www/chatroom-service_socket_backend-socketio
  file:
    path: /var/www/chatroom-service_socket_backend-socketio
    recurse: yes  
    owner: root
    group: root
    mode: 0777
    
    
- name: "(git) git clone git@gitlab.ques98.cn:chatroom/chatroom-service_socket_backend-socketio.git /var/www/chatroom-service_socket_backend-socketio"
  git:
    repo: 'git@gitlab.ques98.cn:chatroom/chatroom-service_socket_backend-socketio.git'
    dest: "/var/www/chatroom-service_socket_backend-socketio"
    version: "{{ 'develop' if branch == 'feature' or branch == 'fea' else branch }}"
    update: yes
    accept_hostkey: yes
  become: no # 使用 vagrant:vagrant git clone 下来， 不使用 root git clone
# chmod -R 700 /root/.ssh/id_rsa
# chmod -R 700 /root/.ssh/id_rsa.pub
# key must be put in root because sudo git clone