- import_tasks: chatroom-mongodb.yml
- import_tasks: chatroom-mysql.yml
- import_tasks: chatroom-nginx.yml

- import_tasks: chatroom-service_other_backend-koa.yml
- import_tasks: chatroom-service_socket_backend-socketio.yml
- import_tasks: chatroom-service_any_frontend-vue.yml
