---
- name: (template) scp tmp/chatroom.js.j2 /tmp/chatroom.js
  template:
    src: tmp/chatroom.js.j2
    dest: /tmp/chatroom.js
    owner: root
    group: root
    mode: 0776
    backup: no
- name: (shell) mongo < /tmp/chatroom.js
  shell: mongo < /tmp/chatroom.js