---
- name: (pause) sleep 10s
  pause:
    seconds: 10
- name: "(shell) sudo masterha_check_status --conf={{ MASTERHA.CONF }}"
  shell: "masterha_check_status --conf={{ MASTERHA.CONF }}"
  register: s_masterha_status
  retries: 3 
  delay: 3
  ignore_errors: yes
- name: (debug) s_masterha_status
  debug: 
    msg: "{{ s_masterha_status }}"