---
- name: "(shell) sudo masterha_check_ssh --conf={{ MASTERHA.CONF }}"
  shell: "masterha_check_ssh --conf={{ MASTERHA.CONF }}"
  register: string_masterha_ssh
  ignore_errors: yes
  when: mysql_ha == 'mha'
- name: (debug) string_masterha_ssh
  run_once: true
  debug: 
    msg: "{{ string_masterha_ssh }}"