---
- name: (yum) yum remove nodejs
  yum: 
    name:
      - nodejs
    state: absent
- name: (yum) yum install nodejs
  yum: 
    name:
      - nodejs
    state: latest
- name: "(command) npm install n -g"
  command: "npm install n -g"
- name: "(command) n {{ node_version }}"
  command: "n {{ node_version }}"
  # notify: 
  #   - debug yum install nodejs