---
- name: Install feature nyga
  hosts: fea-nyga
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/admin168.fea.yml
  pre_tasks:
    - shell: echo 'playbook nyga starts'
  roles:
    - role: nyga
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook nyga ends'
