---
- name: Install feature chatroom-mongodb
  hosts: fea-chatroom-mongodb
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/chatroom.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，chatroom-mongodb 安装开始"
      shell: echo 'playbook chatroom-mongodb starts'
  roles:
    - role: chatroom
      vars: 
        bra: fea
        chatroom_mongodb: true
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，chatroom-mongodb 安装开始"
      shell: echo 'playbook chatroom-mongodb ends'
      
- name: Install feature chatroom-mysql
  hosts: fea-chatroom-mysql
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/chatroom.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，chatroom-mysql 安装开始"
      shell: echo 'playbook chatroom-mysql starts'
  roles:
    - role: chatroom
      vars: 
        bra: fea
        chatroom_mysql: true
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，chatroom-mysql 安装开始"
      shell: echo 'playbook chatroom-mysql ends'
      
      
- name: Install feature chatroom-nginx
  hosts: fea-chatroom-nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/chatroom.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，chatroom-nginx 安装开始"
      shell: echo 'playbook chatroom-nginx starts'
  roles:
    - role: chatroom
      vars: 
        bra: fea
        chatroom_nginx: true
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，chatroom-nginx 安装开始"
      shell: echo 'playbook chatroom-nginx ends'




- name: Install feature chatroom-service_other_backend-koa
  hosts: fea-chatroom-service_other_backend-koa
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/chatroom.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，chatroom-service_other_backend-koa 安装开始"
      shell: echo 'playbook chatroom-service_other_backend-koa starts'
  roles:
    - role: chatroom
      vars: 
        bra: fea
        chatroom_service_other_backend_koa_build: true
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，chatroom-service_other_backend-koa 安装开始"
      shell: echo 'playbook chatroom-service_other_backend-koa ends'
  
- name: Install feature chatroom-service_socket_backend-socketio
  hosts: fea-chatroom-service_socket_backend-socketio
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/chatroom.fea.yml
  pre_tasks:
    - name: "开发 feature 环境，chatroom-service_socket_backend-socketio 安装开始"
      shell: echo 'playbook chatroom-service_socket_backend-socketio starts'
  roles:
    - role: chatroom
      vars:
        bra: fea
        chatroom_service_socket_backend_socketio_build: true

      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "开发 feature 环境，chatroom-service_socket_backend-socketio 安装完毕"
      shell: echo 'playbook chatroom-service_socket_backend-socketio ends'
      
      
- name: Install feature chatroom-service_any_frontend-vue
  hosts: fea-chatroom-service_any_frontend-vue
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/chatroom.fea.yml
  pre_tasks:
    - name: "开发 feature 环境，chatroom-service_any_frontend-vue 安装开始"
      shell: echo 'playbook chatroom-service_any_frontend-vue starts'
  roles:
    - role: chatroom
      vars:
        bra: fea
        chatroom_service_any_frontend_vue_build: true
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "开发 feature 环境，chatroom-service_any_frontend-vue 安装完毕"
      shell: echo 'playbook chatroom-service_any_frontend-vue ends'
      
      
      
- name: Install feature chatroom-service_other_backend-koa
  hosts: fea-chatroom-service_other_backend-koa
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/chatroom.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，chatroom-service_other_backend-koa 安装开始"
      shell: echo 'playbook chatroom-service_other_backend-koa starts'
  roles:
    - role: chatroom
      vars: 
        bra: fea
        chatroom_service_other_backend_koa_pm2: true
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，chatroom-service_other_backend-koa 安装开始"
      shell: echo 'playbook chatroom-service_other_backend-koa ends'
  
- name: Install feature chatroom-service_socket_backend-socketio
  hosts: fea-chatroom-service_socket_backend-socketio
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/chatroom.fea.yml
  pre_tasks:
    - name: "开发 feature 环境，chatroom-service_socket_backend-socketio 安装开始"
      shell: echo 'playbook chatroom-service_socket_backend-socketio starts'
  roles:
    - role: chatroom
      vars:
        bra: fea
        chatroom_service_socket_backend_socketio_pm2: true

      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "开发 feature 环境，chatroom-service_socket_backend-socketio 安装完毕"
      shell: echo 'playbook chatroom-service_socket_backend-socketio ends'
      
      
    

      
     