---
- name: Install feature elasticsearch
  hosts: fea-elasticsearch
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/elasticsearch.fea.yml
  pre_tasks:
    - shell: echo 'playbook elasticsearch starts'
  roles:
    - role: elasticsearch
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook elasticsearch ends'
  vars:
- name: Install develop elesticsearch
  hosts: dev-elasticsearch
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/elasticsearch.dev.yml
  pre_tasks:
    - shell: echo 'playbook elasticsearch starts'
  roles:
    - role: elasticsearch
      vars:
        bra: dev
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook elasticsearch ends'
