
---
- name: Install feature lottery
  hosts: fea-lottery
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/lottery.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，lottery 安装开始"
      shell: echo 'playbook lottery-database-mysql starts'
  roles:
    - role: lottery
      vars:
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，lottery 安装完毕"
      shell: echo 'playbook lottery-database-mysql ends'
      
- name: Install develop lottery
  hosts: dev-lottery
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/lottery.dev.yml
  pre_tasks:
    - name: "开发 develop 环境，lottery 安装开始"
      shell: echo 'playbook lottery starts'
  roles:
    - role: lottery
      vars:
        bra: dev
      when: branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "开发 develop 环境，lottery 安装完毕"
      shell: echo 'playbook lottery ends'