
---
- name: Install feature lottery-service_resource_backend-lumen
  hosts: fea-lottery-service_resource_backend-lumen
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/lottery-service_resource_backend-lumen.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，lottery-service_resource_backend-lumen 安装开始"
      shell: echo 'playbook lottery-service_resource_backend-lumen starts'
  roles:
    - role: lottery-service_resource_backend-lumen
      vars:
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，lottery-service_resource_backend-lumen 安装完毕"
      shell: echo 'playbook lottery-service_resource_backend-lumen ends'
      
- name: Install develop lottery-service_resource_backend-lumen
  hosts: dev-lottery-service_resource_backend-lumen
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/lottery-service_resource_backend-lumen.dev.yml
  pre_tasks:
    - name: "开发 develop 环境，lottery-service_resource_backend-lumen 安装开始"
      shell: echo 'playbook lottery-service_resource_backend-lumen starts'
  roles:
    - role: lottery-service_resource_backend-lumen
      vars:
        bra: dev
      when: branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "开发 develop 环境，lottery-service_resource_backend-lumen 安装完毕"
      shell: echo 'playbook lottery-service_resource_backend-lumen ends'