---
- name: Install feature node
  hosts: fea-node
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/node.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Node 安装开始"
      shell: echo 'playbook node starts'
  roles:
    - role: node
      vars:
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，Node 安装完毕"
      shell: echo 'playbook node ends'
- name: Install develop node
  hosts: dev-node
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/node.dev.yml
  pre_tasks:
    - name: "开发 develop 环境，Node 安装开始"
      shell: echo 'playbook node starts'
  roles:
    - role: node
      vars:
        bra: dev
      when: branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "开发 develop 环境，Node 安装完毕"
      shell: echo 'playbook node ends'
