---
- name: "Install feature php"
  hosts: fea-php
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/php.fea.yml
  pre_tasks:
    - shell: "echo 'playbook php starts' "
  roles:
    - role: php
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook php ends'
- name: Install develop php
  hosts: dev-php
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/php.dev.yml
  pre_tasks:
    - shell: echo 'playbook php starts'
  roles:
    - role: php
      vars:
        bra: dev
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook php ends'
