---
# PYTHON 这里有一个坑，Yum 指令 , Ansible 指令 都是相依於 PYTHON 
# 不可随意改变 python 版本，
# 请用 /usr/bin/python2 /usr/bin/python3

- name: "Install feature python"
  hosts: fea-python # Ansible tower cannt remove or reinstall python
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/python.fea.yml
    - ./../group_vars/timedatectl.fea.yml
  pre_tasks:
    - shell: "echo 'playbook python starts' "
  roles:
    - role: python
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook python ends'
- name: Install develop python
  hosts: dev-python
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/python.fea.yml
  pre_tasks:
    - shell: echo 'playbook python starts'
  roles:
    - role: python
      vars:
        bra: dev
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook python ends'
