---
- name: Install feature redis
  hosts: fea-redis
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/redis.fea.yml
  pre_tasks:
    - shell: echo 'playbook redis starts'
  roles:
    - role: redis
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook redis ends'
  vars:
- name: Install develop redis
  hosts: dev-redis
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/redis.dev.yml
  pre_tasks:
    - shell: echo 'playbook redis starts'
  roles:
    - role: redis
      vars:
        bra: dev
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook redis ends'
